### PR TITLE
gui.js: fixed save button breaking with complex songs

### PR DESCRIPTION
**Pull request by mrdoob**
This was a simple fix.

Here you can see it without the whitespaces clean up: https://github.com/mrdoob/soundbox/commit/f092cf4917fecc316a12cd5ff51b6ca732ea092a?w=1

### CODE REVIEW

**Comment by mbitsnbites** [comment]
Thanks! Will review when I'm at a proper computer terminal (great with the trailing whitespace fixes - but would be easier to review if they were in a separate commit).

**Comment by mrdoob** [comment]
Sorry, I didn't notice my editor did these changes.
The link I shared is the same commit but with `?w=1` hiding the whitespace changes.

**Comment by mrdoob** [comment]
This also works: https://github.com/mbitsnbites/soundbox/pull/79/files?w=1

**Comment by mbitsnbites** [comment]
Brilliant! (I should have known about that feature)

**Comment by mbitsnbites** [comment]
Will update the public site asap

**Comment by mrdoob** [comment]
Have you considered using Github Pages?

You can make https://sb.bitsnbites.eu/ point to this repo (you can chose the branch) and it'll update automatically after every commit.

You need to add a [CNAME](https://github.com/mrdoob/frame.js/blob/master/CNAME) file to the repo and then fiddle with the DNSs a bit.

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages

**Comment by mrdoob** [comment]
In the meantime, we're using https://mrdoob.github.io/soundbox/ 👌

**Pull request merged**
